// @ts-nocheck
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getHeaderInfo: () => __TAURI_INVOKE<HeaderInfo>("get_header_info"),
	getDpsPlayerWindow: () => __TAURI_INVOKE<PlayersWindow>("get_dps_player_window"),
	getDpsSkillWindow: (playerUidStr: string) => typedError<SkillsWindow, string>(__TAURI_INVOKE("get_dps_skill_window", { playerUidStr })),
	getDpsBossOnlyPlayerWindow: () => __TAURI_INVOKE<PlayersWindow>("get_dps_boss_only_player_window"),
	getDpsBossOnlySkillWindow: (playerUidStr: string) => typedError<SkillsWindow, string>(__TAURI_INVOKE("get_dps_boss_only_skill_window", { playerUidStr })),
	getHealPlayerWindow: () => __TAURI_INVOKE<PlayersWindow>("get_heal_player_window"),
	getHealSkillWindow: (playerUidStr: string) => typedError<SkillsWindow, string>(__TAURI_INVOKE("get_heal_skill_window", { playerUidStr })),
	submitPendingWebhook: (image: number[]) => __TAURI_INVOKE<void>("submit_pending_webhook", { image }),
	resetEncounterWithImage: (image: number[]) => __TAURI_INVOKE<void>("reset_encounter_with_image", { image }),
	resetEncounter: () => __TAURI_INVOKE<void>("reset_encounter"),
	togglePauseEncounter: () => __TAURI_INVOKE<void>("toggle_pause_encounter"),
	hardReset: () => __TAURI_INVOKE<void>("hard_reset"),
	quitApp: () => __TAURI_INVOKE<void>("quit_app"),
	getTestPlayerWindow: () => __TAURI_INVOKE<PlayersWindow>("get_test_player_window"),
	getTestSkillWindow: (playerUid: string) => typedError<SkillsWindow, string>(__TAURI_INVOKE("get_test_skill_window", { playerUid })),
	setBptimerEnabled: (enabled: boolean) => __TAURI_INVOKE<void>("set_bptimer_enabled", { enabled }),
	setWebhookEnabled: (enabled: boolean) => __TAURI_INVOKE<void>("set_webhook_enabled", { enabled }),
	/**
	 *  List the local player's parsed gear modules. Empty until the game has sent
	 *  the player's container snapshot (the UI prompts the user to open their
	 *  character / re-log if so).
	 */
	getModules: () => __TAURI_INVOKE<ModuleInfo[]>("get_modules"),
	// The list of selectable module attributes (for the optimizer's pickers).
	getModuleAttributes: () => __TAURI_INVOKE<AttrMeta[]>("get_module_attributes"),
	// Run the built-in module optimizer over the local player's modules.
	optimizeModules: (request: OptimizeRequest) => typedError<ModuleSolution[], string>(__TAURI_INVOKE("optimize_modules", { request })),
};

/* Types */
// Serializable attribute metadata for the frontend attribute pickers.
export type AttrMeta = {
	id: number,
	name: string,
	nameCn: string,
	special: boolean,
};

export type AttrValue = {
	name: string,
	value: number,
};

export type HeaderInfo = {
	totalDps: number,
	totalDmg: number,
	elapsedMs: number,
	timeLastCombatPacketMs: number,
};

// Module category, derived from the module's `config_id`.
export type ModuleCategory = "Attack" | "Guardian" | "Support";

// A parsed gear module.
export type ModuleInfo = {
	/**
	 *  Unique item id. Serialized as a string because these ids routinely
	 *  exceed `2^53` and would lose precision as a JS number.
	 */
	uuid: string,
	configId: number,
	name: string,
	category: ModuleCategory,
	quality: number,
	parts: ModulePart[],
};

// One attribute roll on a module.
export type ModulePart = {
	id: number,
	name: string,
	value: number,
	special: boolean,
};

export type ModuleSolution = {
	rank: number,
	score: number,
	totalValue: number,
	modules: ModuleInfo[],
	breakdown: AttrValue[],
};

export type OptimizeRequest = {
	// `"All"`, `"Attack"`, `"Guardian"`, or `"Support"`.
	category: string,
	// Attribute ids to maximize (empty = maximize overall power).
	targetAttrs: number[],
	// Attribute ids to avoid: any module carrying one of these is dropped.
	excludeAttrs: number[],
	// A module must carry at least this many of `target_attrs` to be used.
	matchCount: number,
	// Combination size: 4 or 5.
	comboSize: number,
	// Number of ranked solutions to return.
	topN: number,
};

export type PlayerRow = {
	uid: number,
	abilityScore: number,
	className: string,
	classSpecName: string,
	name: string,
	totalValue: number,
	valuePerSec: number,
	valuePct: number,
	critRate: number,
	critValueRate: number,
	luckyRate: number,
	luckyValueRate: number,
	hits: number,
	hitsPerMinute: number,
};

export type PlayersWindow = {
	playerRows: PlayerRow[],
	localPlayerUid: number,
	topValue: number,
};

export type SkillRow = {
	uid: number,
	name: string,
	totalValue: number,
	valuePerSec: number,
	valuePct: number,
	critRate: number,
	critValueRate: number,
	luckyRate: number,
	luckyValueRate: number,
	hits: number,
	hitsPerMinute: number,
};

export type SkillsWindow = {
	inspectedPlayer: PlayerRow,
	skillRows: SkillRow[],
	localPlayerUid: number,
	topValue: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

